#!/bin/sh

# This is run by go generate from frontend.go.
# It generates the locales.go file.
# And builds the frontend using npm.

set -e
# Install dependencies.
npm ci

# Build the frontend 'dist' directory.
npm run build

# Get all the locales. Remove the folder prefix and the '.json' suffix.
locales=$(ls -1 src/includes/locale/*.json | sed 's#src/includes/locale/\(.*\)\.json#\1#g')

echo "Creating locales.go..."

# Create the locales.go file.
cat <<EOF > locales.go
package frontend

/* This file is generated by generate.sh. Do not edit it directly. */

//nolint:gochecknoglobals
var langs = []string{
EOF

# Add each locale to the file.
for locale in $locales; do
 # We use a real tab in this string because windows sucks.
 echo "	\"$locale\"," >> locales.go
done

# Close the file.
echo "}" >> locales.go
