#!/bin/sh

# This is run by go generate from frontend.go.
# It generates the locales.go file.
# And builds the frontend using npm.

set -e

# Generate OpenAPI 3 specs. swag v2 still names the files *_swagger.json.
SWAG=github.com/swaggo/swag/v2/cmd/swag@v2.0.0-rc5

go run ${SWAG} i --v3.1 \
    --parseDependency --instanceName api --outputTypes json \
    --parseInternal --tags !System,!Integrations,!Files --dir ../ -g main.go --output ./public
mv ./public/api_swagger.json ./public/api_openapi.json

go run ${SWAG} i --v3.1 \
    --parseDependency --instanceName ui --outputTypes json \
    --parseInternal --tags System,Integrations,Files --dir ../ -g pkg/client/handlers_gui.go --output ./public
mv ./public/ui_swagger.json ./public/ui_openapi.json
rm -f ./public/api_swagger.json ./public/ui_swagger.json

# Install dependencies.
npm install

# Build the frontend 'dist' directory.
npm run build

# Get all the locales. Remove the folder prefix and the '.json' suffix.
locales=$(ls -1 src/includes/locale/*.json | sed 's#src/includes/locale/\(.*\)\.json#\1#g')

echo "Creating locales.go..."

# Create the locales.go file.
cat <<EOF > locales.go
package frontend

/* This file is generated by generate.sh. Do not edit it directly. */

//nolint:gochecknoglobals
var langs = []string{
EOF

# Add each locale to the file.
for locale in $locales; do
 # We use a real tab in this string because windows sucks.
 echo "	\"$locale\"," >> locales.go
done

# Close the file.
echo "}" >> locales.go
