package frontend

/* This file is generated by generate.sh. Do not edit it directly. */

//nolint:gochecknoglobals
var langs = []string{
	"de",
	"en",
	"es",
	"fi",
	"fr",
	"hu",
	"it",
	"nl",
	"pl",
	"pt",
	"sv",
	"zh_Hant",
}
