// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://notifiarr.com",
        "contact": {
            "name": "Notifiarr Support",
            "url": "https://notifiarr.com/discord",
            "email": "support@notifiarr.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/Notifiarr/notifiarr/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/plex": {
            "post": {
                "description": "Accepts a Plex webhook; when conditions are satisfied sends a notification to the website,\nand may include snapshot data and/or fetched session data.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "plex"
                ],
                "summary": "Accepts a Plex Media Server Webhook",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Plex Token or Client API Key",
                        "name": "token",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "webhook payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/plex.IncomingWebhook"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "accepted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "208": {
                        "description": "ignored",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "bad input",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "bad token or api key",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "plex.GUID": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "plex.IncomingWebhook": {
            "type": "object",
            "properties": {
                "Account": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "integer"
                        },
                        "thumb": {
                            "type": "string"
                        },
                        "title": {
                            "type": "string"
                        }
                    }
                },
                "Metadata": {
                    "$ref": "#/definitions/plex.WebhookMetadata"
                },
                "Player": {
                    "type": "object",
                    "properties": {
                        "local": {
                            "type": "boolean"
                        },
                        "publicAddress": {
                            "type": "string"
                        },
                        "title": {
                            "type": "string"
                        },
                        "uuid": {
                            "type": "string"
                        }
                    }
                },
                "Server": {
                    "type": "object",
                    "properties": {
                        "title": {
                            "type": "string"
                        },
                        "uuid": {
                            "type": "string"
                        }
                    }
                },
                "event": {
                    "type": "string"
                },
                "owner": {
                    "type": "boolean"
                },
                "rating": {
                    "type": "number"
                },
                "user": {
                    "type": "boolean"
                }
            }
        },
        "plex.WebhookMetadata": {
            "type": "object",
            "properties": {
                "Guid": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/plex.GUID"
                    }
                },
                "Rating": {
                    "description": "bullshit."
                },
                "addedAt": {
                    "type": "integer"
                },
                "art": {
                    "type": "string"
                },
                "audienceRating": {
                    "type": "number"
                },
                "audienceRatingImage": {
                    "type": "string"
                },
                "contentRating": {
                    "type": "string"
                },
                "duration": {
                    "type": "number"
                },
                "grandparentArt": {
                    "type": "string"
                },
                "grandparentGuid": {
                    "type": "string"
                },
                "grandparentKey": {
                    "type": "string"
                },
                "grandparentRatingKey": {
                    "type": "string"
                },
                "grandparentTheme": {
                    "type": "string"
                },
                "grandparentThumb": {
                    "type": "string"
                },
                "grandparentTitle": {
                    "type": "string"
                },
                "guid": {
                    "type": "string"
                },
                "index": {
                    "type": "integer"
                },
                "key": {
                    "type": "string"
                },
                "lastViewedAt": {
                    "type": "integer"
                },
                "librarySectionID": {
                    "description": "int (plex) or string (session tracker)"
                },
                "librarySectionKey": {
                    "type": "string"
                },
                "librarySectionTitle": {
                    "type": "string"
                },
                "librarySectionType": {
                    "type": "string"
                },
                "originallyAvailableAt": {
                    "type": "string"
                },
                "parentGuid": {
                    "type": "string"
                },
                "parentIndex": {
                    "type": "integer"
                },
                "parentKey": {
                    "type": "string"
                },
                "parentRatingKey": {
                    "type": "string"
                },
                "parentThumb": {
                    "type": "string"
                },
                "parentTitle": {
                    "type": "string"
                },
                "parentYear": {
                    "type": "integer"
                },
                "primaryExtraKey": {
                    "type": "string"
                },
                "rating": {
                    "type": "number"
                },
                "ratingImage": {
                    "type": "string"
                },
                "ratingKey": {
                    "type": "string"
                },
                "studio": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "tagline": {
                    "type": "string"
                },
                "thumb": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "titleSort": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "integer"
                },
                "viewOffset": {
                    "type": "number"
                },
                "year": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Notifiarr Client API",
	Description:      "Monitors local services and sends notifications.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
