#!/usr/bin/env bash

# This file is designed to run as build hook for Automated Builds on Docker.com.
# This always run local to the Dockerfile folder, so the path is ../..
pushd ../..
source settings.sh

docker buildx create --use

read -r -d '' CMD << EOF 
 docker buildx build --load --tag current \
  --platform linux/amd64,linux/arm64/v8,linux/arm \
  --build-arg "BUILD_DATE=${DATE}" \
  --build-arg "BUILD_FLAGS=${BUILD_FLAGS}" \
  --build-arg "COMMIT=${COMMIT}" \
  --build-arg "VERSION=${VERSION}-${ITERATION}" \
  --build-arg "LICENSE=${LICENSE}" \
  --build-arg "DESC=${DESC}" \
  --build-arg "VENDOR=${VENDOR}" \
  --build-arg "AUTHOR=${MAINT}" \
  --build-arg "BINARY=${BINARY}" \
  --build-arg "SOURCE_URL=${SOURCE_URL}" \
  --file ${DOCKERFILE_PATH} .
EOF

echo "Running command: ${CMD}"
eval $CMD

popd
