#!/usr/bin/env bash

# This file is designed to run as build hook for Automated Builds on Docker.com.
# This always run local to the Dockerfile folder, so the path is ../..
pushd ../..
source settings.sh

docker buildx create --use

read -r -d '' BUILD_ARGS << EOF
--build-arg "BUILD_DATE=${DATE}" \
--build-arg "BUILD_FLAGS=${BUILD_FLAGS}" \
--build-arg "COMMIT=${COMMIT}" \
--build-arg "VERSION=${VERSION}-${ITERATION}" \
--build-arg "LICENSE=${LICENSE}" \
--build-arg "DESC=${DESC}" \
--build-arg "VENDOR=${VENDOR}" \
--build-arg "AUTHOR=${MAINT}" \
--build-arg "BINARY=${BINARY}" \
--build-arg "SOURCE_URL=${SOURCE_URL}" \
--file ${DOCKERFILE_PATH} .
EOF

echo "Build Args: ${BUILD_ARGS}"
eval "docker buildx build --load --tag current:amd64 --platform linux/amd64 $BUILD_ARGS"
eval "docker buildx build --load --tag current:arm64 --platform linux/arm64/v8 $BUILD_ARGS"
eval "docker buildx build --load --tag current:arm --platform linux/arm $BUILD_ARGS"
echo "Done Building."

