#!/bin/bash

# This upgrades the docker client on the Docker Cloud server to a version
# that contains the `docker manifest` command. To use `docker manifest`
# set `DOCKER_CLI_EXPERIMENTAL=enabled` in your build environment.

docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
