#!/usr/bin/env bash

pushd ../..
source settings.sh

TAGS="$SOURCE_BRANCH"
if [ "v$VERSION" = "$SOURCE_BRANCH" ]; then
  TAGS="$VERSION"

  echo $SOURCE_BRANCH | grep -q -- -
  if [ "$?" = "1" ]; then
    # tag does not contain a dash, so assume it's a prod tag.
    TAGS="$TAGS latest stable $(echo $VERSION | cut -d. -f1,2) $(echo $VERSION | cut -d. -f1)"
  fi
fi


for tag in $TAGS; do
  echo "Pushing tag: $DOCKER_REPO:$tag"
  docker buildx build --push --platform linux/amd64,linux/arm64/v8,linux/arm -t $DOCKER_REPO:$tag --file ${DOCKERFILE_PATH} .
done

