#!/usr/bin/env bash

# This file is designed to run as build hook for Automated Builds on Docker.com.
# This always run local to the Dockerfile folder, so the path is ../..
pushd ../..
source settings.sh

if [ "v$VERSION" = "$SOURCE_BRANCH" ]; then
  TAGS="--tag $VERSION"

  echo $SOURCE_BRANCH | grep -q -- -
  if [ "$?" = "1" ]; then
    # tag does not contain a dash, so assume it's a prod tag.
    TAGS="$TAGS --tag latest --tag stable --tag $(echo $VERSION | cut -d. -f1,2) --tag $(echo $VERSION | cut -d. -f1)"
  fi
else
  TAGS="--tag ${SOURCE_BRANCH}"
fi

docker push $TAGS