#!/usr/bin/env bash
pushd ../..
source settings.sh

TAGS="$DOCKER_REPO:${SOURCE_BRANCH}"
if [ "v$VERSION" = "$SOURCE_BRANCH" ]; then
  TAGS="$DOCKER_REPO:$VERSION"

  echo $SOURCE_BRANCH | grep -q -- -
  if [ "$?" = "1" ]; then
    # tag does not contain a dash, so assume it's a prod tag.
    TAGS="$TAGS $DOCKER_REPO:latest $DOCKER_REPO:stable $DOCKER_REPO:$(echo $VERSION | cut -d. -f1,2) $DOCKER_REPO:$(echo $VERSION | cut -d. -f1)"
  fi
fi

for tag in $TAGS; do
  docker tag current $tag
  docker push $tag
done