{
 "title": "Notifiarr Client",
 "description": "Dashboard to visualize the Notifiarr Client metrics exported to Prometheus.",
 "tags": [ "notifiarr" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "apps",
    "query": {
     "query": "label_values(notifiarr_client_integrations,app)"
    }
   },
   {
    "name": "log_lines",
    "query": {
     "query": "label_values(notifiarr_client_log_files{name=~\".*Lines.*\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Actions & File Watcher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Action Counters",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "notifiarr_client_action_counters",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "File Watcher Matches",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    { "expr": "notifiarr_client_file_watcher", "legendFormat": "{{name}}" }
   ]
  },
  { "title": "Web Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(notifiarr_client_http_requests{name=~\".*Bytes.*\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "notifiarr_client_http_requests{name!~\".*Bytes.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "API Request Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "rate(notifiarr_client_api_requests{name=~\".*Bytes.*\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Log File Data Written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(notifiarr_client_log_files{name=~\".*Bytes.*\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "API Request Counts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "notifiarr_client_api_requests{name!~\".*Bytes.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Log File Lines Written",
   "type": "stat",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "notifiarr_client_log_files{name!~\".*Bytes.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Requests to Website",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(notifiarr_client_website{name=\"POST Bytes Received\"}[1m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "rate(notifiarr_client_website{name=\"POST Bytes Sent\"}[1m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "notifiarr_client_website{name=\"POST Requests\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Health Checks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Health Check Counters",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "notifiarr_client_health_checks{name=\"Total\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Total Health Checks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "notifiarr_client_health_checks{name=\"Total\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "OK Health Checks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "notifiarr_service_checks{name=\"OK\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Warning Check Totals",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "notifiarr_service_checks{name=\"Warning\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Critical Check Totals",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "notifiarr_service_checks{name=\"Critical\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Unknown Check Totals",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 90 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "notifiarr_service_checks{name=\"Unknown\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Integration Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "$apps",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 98 },
   "repeat": "apps",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(notifiarr_client_integrations{app=~\"$apps\", name=~\"POST Bytes Received|POST Bytes Sent|GET Bytes Received\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "notifiarr_client_integrations{app=~\"$apps\", name!~\"POST Bytes Received|POST Bytes Sent|GET Bytes Received\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}