// Icon mapping from FontAwesome names to Phosphor components
// Phosphor Icons: https://phosphoricons.com/
import {
  Apple,
  ArrowDown,
  ArrowUp,
  ArrowsClockwise,
  ArrowsCounterClockwise,
  ArrowsDownUp,
  ArrowSquareOut,
  ArrowUUpLeft,
  Book,
  Buildings,
  Camera,
  ChartLine,
  ChartLineUp,
  ChartNetwork,
  Check,
  CheckCircle,
  Checks,
  Circle,
  CircleNotch,
  Clock,
  CloudArrowDown,
  CloudArrowUp,
  Code,
  Command,
  Cpu,
  Cube,
  Desktop,
  DownloadSimple,
  Eye,
  EyeSlash,
  FileMagnifyingGlass,
  FileText,
  Flask,
  Folder,
  FolderOpen,
  GameController,
  GitDiff,
  GlobeSimple,
  Graph,
  HardDrive,
  HardDrives,
  Heartbeat,
  House,
  HouseLine,
  Key,
  Lightning,
  Link,
  LinkSimple,
  LinuxLogo,
  List,
  ListBullets,
  ListChecks,
  MagnifyingGlass,
  MapPin,
  Microchip,
  Moon,
  PingPong,
  Planet,
  Play,
  PlayCircle,
  Power,
  Question,
  QuestionMark,
  Rocket,
  Rows,
  Satellite,
  SealQuestion,
  Server,
  Sliders,
  SlidersHorizontal,
  Snake,
  Sparkle,
  SpinnerGap,
  Splash,
  Star,
  Sun,
  Table,
  Tent,
  Terminal,
  Trash,
  TreeStructure,
  Translate,
  Upload,
  User,
  UserCircle,
  UserGear,
  UsersThree,
  Video,
  Warning,
  Webhooks,
  WindowsLogo,
  X,
  XCircle,
  type IconWeight,
} from 'phosphor-svelte'
import type { Component } from 'svelte'

// Icon type definition
export interface IconDef {
  icon: Component
  weight?: IconWeight
}

// Weight mappings for visual variety
type WeightType = 'light' | 'regular' | 'bold' | 'fill' | 'duotone'

// Create icon definition helper
const icon = (component: Component, weight: WeightType = 'duotone'): IconDef => ({
  icon: component,
  weight: weight as IconWeight,
})

// FontAwesome to Phosphor mapping
// Using duotone weight by default for that cool dual-tone look
export const icons = {
  // Brand icons
  faApple: icon(Apple, 'fill'),
  faDocker: icon(Cube, 'duotone'), // Docker → Cube (container)
  faFreebsd: icon(Desktop, 'duotone'),
  faLinux: icon(LinuxLogo, 'fill'),
  faWindows: icon(WindowsLogo, 'fill'),

  // Navigation & Actions
  faArrowDownFromBracket: icon(ArrowDown, 'duotone'),
  faArrowDownShortWide: icon(ArrowsDownUp, 'duotone'),
  faArrowDownToBracket: icon(ArrowDown, 'duotone'),
  faArrowProgress: icon(ChartLineUp, 'duotone'),
  faArrowRightArrowLeft: icon(ArrowsClockwise, 'duotone'),
  faArrowRotateRight: icon(ArrowsClockwise, 'duotone'),
  faArrowUpFromBracket: icon(Upload, 'duotone'),
  faArrowUpShortWide: icon(ArrowsDownUp, 'duotone'),
  faArrowUpToArc: icon(ArrowUp, 'duotone'),
  faArrowsRepeat: icon(ArrowsClockwise, 'duotone'),
  faArrowsRotate: icon(ArrowsClockwise, 'duotone'),
  faArrowsSpin: icon(SpinnerGap, 'duotone'),
  faSwapArrows: icon(ArrowsCounterClockwise, 'duotone'),

  // Status & Feedback
  faCheck: icon(Check, 'bold'),
  faCheckDouble: icon(Checks, 'duotone'),
  faCircleCheck: icon(CheckCircle, 'duotone'),
  faCirclePlay: icon(PlayCircle, 'duotone'),
  faCircleXmark: icon(XCircle, 'duotone'),
  faExclamationCircle: icon(Warning, 'duotone'),
  faExclamationTriangle: icon(Warning, 'duotone'),
  faQuestion: icon(Question, 'duotone'),
  faQuestionCircle: icon(SealQuestion, 'duotone'),
  faSpinner: icon(SpinnerGap, 'duotone'),
  faXmarkLarge: icon(X, 'bold'),

  // Files & Folders
  faBook: icon(Book, 'duotone'),
  faFileWaveform: icon(FileText, 'duotone'),
  faFolderOpen: icon(FolderOpen, 'duotone'),
  faListTimeline: icon(Rows, 'duotone'),
  faListTree: icon(TreeStructure, 'duotone'),
  faListCheck: icon(ListChecks, 'duotone'),
  faTableCellsLarge: icon(Table, 'duotone'),
  faTrashAlt: icon(Trash, 'duotone'),

  // System & Hardware
  faBuildingCircleCheck: icon(Buildings, 'duotone'),
  faChartLine: icon(ChartLine, 'duotone'),
  faChartNetwork: icon(ChartNetwork, 'duotone'),
  faClock: icon(Clock, 'duotone'),
  faCloudDownload: icon(CloudArrowDown, 'duotone'),
  faCloudUpload: icon(CloudArrowUp, 'duotone'),
  faCodeCompare: icon(GitDiff, 'duotone'),
  faCodeSimple: icon(Code, 'duotone'),
  faCompactDisc: icon(HardDrive, 'duotone'),
  faCubes: icon(Cube, 'duotone'),
  faDisplayChartUpCircleCurrency: icon(ChartLineUp, 'duotone'),
  faGlobePointer: icon(GlobeSimple, 'duotone'),
  faHardDrive: icon(HardDrives, 'duotone'),
  faHeartPulse: icon(Heartbeat, 'duotone'),
  faMicrochip: icon(Microchip, 'duotone'),
  faNfcSymbol: icon(Cpu, 'duotone'),
  faServer: icon(Server, 'duotone'),
  faSlidersH: icon(SlidersHorizontal, 'duotone'),

  // Apps & Features
  faCameraRetro: icon(Camera, 'duotone'),
  faClapperboardPlay: icon(Video, 'duotone'),
  faCommand: icon(Command, 'duotone'),
  faDownload: icon(DownloadSimple, 'duotone'),
  faFlaskGear: icon(Flask, 'duotone'),
  faHexagonNodesBolt: icon(Lightning, 'duotone'),
  faHouseChimneyHeart: icon(HouseLine, 'duotone'),
  faHouseLock: icon(House, 'duotone'),
  faLanguage: icon(Translate, 'duotone'),
  faLinkHorizontal: icon(Link, 'duotone'),
  faLinkSimple: icon(LinkSimple, 'duotone'),
  faLocationQuestion: icon(MapPin, 'duotone'),
  faPingPongPaddleBall: icon(PingPong, 'duotone'),
  faPowerOff: icon(Power, 'duotone'),
  faPrintMagnifyingGlass: icon(FileMagnifyingGlass, 'duotone'),
  faRedo: icon(ArrowsClockwise, 'duotone'),
  faRightToLine: icon(ArrowSquareOut, 'duotone'),
  faRotate: icon(ArrowsClockwise, 'duotone'),
  faSatellite: icon(Satellite, 'duotone'),
  faSplotch: icon(Splash, 'duotone'),
  faStaffSnake: icon(Snake, 'duotone'),
  faStarfighter: icon(Rocket, 'duotone'),
  faStars: icon(Sparkle, 'duotone'),
  faStarship: icon(Rocket, 'duotone'),
  faSun: icon(Sun, 'duotone'),
  faTents: icon(Tent, 'duotone'),
  faTerminal: icon(Terminal, 'duotone'),
  faVideo: icon(Video, 'duotone'),
  faWebhook: icon(Webhooks, 'duotone'),

  // Users
  faUserAlt: icon(User, 'duotone'),
  faUserBountyHunter: icon(UserGear, 'duotone'),
  faUserCowboy: icon(UserCircle, 'duotone'),
  faUserHairMullet: icon(User, 'duotone'),
  faUserNinja: icon(UserGear, 'duotone'),
  faUserSecret: icon(UserGear, 'duotone'),

  // View controls
  faColors: icon(Sparkle, 'duotone'),
  faCompress: icon(ArrowsCounterClockwise, 'duotone'),
  faExpand: icon(ArrowsClockwise, 'duotone'),
  faEye: icon(Eye, 'duotone'),
  faEyeEvil: icon(Eye, 'duotone'),
  faEyeSlash: icon(EyeSlash, 'duotone'),
} as const

// Export individual icons for direct import
export const {
  faApple, faDocker, faFreebsd, faLinux, faWindows,
  faArrowDownFromBracket, faArrowDownShortWide, faArrowDownToBracket,
  faArrowProgress, faArrowRightArrowLeft, faArrowRotateRight,
  faArrowUpFromBracket, faArrowUpShortWide, faArrowUpToArc,
  faArrowsRepeat, faArrowsRotate, faArrowsSpin, faSwapArrows,
  faCheck, faCheckDouble, faCircleCheck, faCirclePlay, faCircleXmark,
  faExclamationCircle, faExclamationTriangle, faQuestion, faQuestionCircle,
  faSpinner, faXmarkLarge, faBook, faFileWaveform, faFolderOpen,
  faListTimeline, faListTree, faListCheck, faTableCellsLarge, faTrashAlt,
  faBuildingCircleCheck, faChartLine, faChartNetwork, faClock,
  faCloudDownload, faCloudUpload, faCodeCompare, faCodeSimple,
  faCompactDisc, faCubes, faDisplayChartUpCircleCurrency, faGlobePointer,
  faHardDrive, faHeartPulse, faMicrochip, faNfcSymbol, faServer, faSlidersH,
  faCameraRetro, faClapperboardPlay, faCommand, faDownload, faFlaskGear,
  faHexagonNodesBolt, faHouseChimneyHeart, faHouseLock, faLanguage,
  faLinkHorizontal, faLinkSimple, faLocationQuestion, faPingPongPaddleBall,
  faPowerOff, faPrintMagnifyingGlass, faRedo, faRightToLine, faRotate,
  faSatellite, faSplotch, faStaffSnake, faStarfighter, faStars, faStarship,
  faSun, faTents, faTerminal, faVideo, faWebhook, faUserAlt, faUserBountyHunter,
  faUserCowboy, faUserHairMullet, faUserNinja, faUserSecret, faColors,
  faCompress, faExpand, faEye, faEyeEvil, faEyeSlash,
} = icons

// Type for icon names
export type IconName = keyof typeof icons

