#!/bin/bash -x

# Deploys a new aur PKGBUILD file to a github repo: $AUREPO
# Requires SSH credentials in ssh-agent to work.
# Run by Travis-CI when a new release is created on GitHub.
# Do not edit this file.

source settings.sh

make aur

git config --global user.email "${BINARY}@auto.releaser"
git config --global user.name "${BINARY}-auto-releaser"

rm -rf aur_release_repo
git clone git@github.com-aurepo:${AUREPO}.git aur_release_repo

mkdir -p "aur_release_repo/${BINARY}"
cp aur/* "aur_release_repo/${BINARY}/"
pushd aur_release_repo
git add ${BINARY}
git commit -m "Update ${BINARY} on Release: v${VERSION}-${ITERATION}"
git push
popd
