#!/bin/bash -x

# Deploys a new homebrew formula file to a github homebrew formula repo: $HBREPO
# Requires SSH credentials in ssh-agent to work.
# Run by Travis-CI when a new release is created on GitHub.
# Do not edit this file.

source settings.sh

SHA256=${curl -sL https://github.com/Notifiarr/notifiarr/archive/v${VERSION}.tar.gz | openssl dgst -r -sha256}

# Creating formula from template using sed.
sed -e "s/{{Version}}/${VERSION}/g" \
  -e "s/{{Iter}}/${ITERATION}/g" \
  -e "s/{{SHA256}}/${SHA256}/g" \
  -e "s/{{Desc}}/${DESC}/g" \
  -e "s%{{SOURCE_URL}}%${SOURCE_URL}%g" \
  -e "s%{{SOURCE_PATH}}%${SOURCE_PATH}%g" \
  -e "s%{{CONFIG_FILE}}%${CONFIG_FILE}%g" \
  -e "s%{{Class}}%Notifiarr%g" \
  init/homebrew/service.rb.tmpl | tee notifiarr.rb

git config --global user.email "notifiarr@auto.releaser"
git config --global user.name "notifiarr-auto-releaser"

rm -rf homebrew_release_repo
git clone git@github.com:Notifiarr/homebrew-mugs.git homebrew_release_repo

# If a bitly token file exists, we'll use that to shorten the link (and allow download counting).
if [ -f "bitly_token" ]; then
  API=https://api-ssl.bitly.com/v4/bitlinks
  # Request payload. In single quotes with double quotes escaped. :see_no_evil:
  JSON='{\"domain\": \"bit.ly\",\"title\": \"notifiarr.v${VERSION}-${ITERATION}.tgz\", \
    \"tags\": [\"notifiarr\"], \"long_url\": \"${SOURCE_PATH}\"}'
  # Request with headers and data. Using bash -c to hide token from bash -x in travis logs.
  OUT=${bash -c "curl -s -X POST -H 'Content-type: application/json' ${API} -H \"\$(<bitly_token)\" -d \"${JSON}\""}
  # Extract link from reply.
  LINK="${echo ${OUT} | jq -r .link | sed 's/http:/https:/'}?v=v${VERSION}"
  # Replace link in formula.
  sed "s#^  url.*\$#  url \"${LINK}\"#" notifiarr.rb > notifiarr.rb.new
  if [ "$?" = "0" ] && [ "$LINK" != "null?v=v${VERSION}" ] && [ "$LINK" != "?v=v${VERSION}" ]; then
    mv notifiarr.rb.new notifiarr.rb
  fi
fi

cp notifiarr.rb homebrew_release_repo/Formula
pushd homebrew_release_repo
git add Formula/notifiarr.rb
git commit -m "Update notifiarr on Release: v${VERSION}-${ITERATION}"
git push
popd
