FROM ubuntu:26.04@sha256:da6fc2be547864451aa253836dd926da33623312df4a9a243e35dc877c378a78

ARG TARGETPLATFORM
ARG TARGETARCH
COPY --chmod=755 ${TARGETPLATFORM}/notifiarr /notifiarr

RUN DEBIAN_FRONTEND=noninteractive apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates curl smartmontools ipmitool zfsutils-linux sysstat libncurses6 tzdata \
    && curl -sSo /notifiarr.tgz \
        "https://raw.githubusercontent.com/Notifiarr/build-dependencies/main/notifiarr-docker-${TARGETARCH}.tgz" \
    && tar -zxf /notifiarr.tgz -C / \
    && rm -f /notifiarr.tgz \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV TZ=UTC
ENV PATH=/bin:/usr/bin:/sbin:/usr/sbin
ENV USER=root

EXPOSE 5454
ENTRYPOINT ["/notifiarr"]
