FROM alpine:3.24@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6

ARG TARGETPLATFORM
COPY --chmod=755 ${TARGETPLATFORM}/notifiarr /notifiarr

# iostat from Alpine sysstat is the wrong version for snapshots.
RUN apk add --no-cache ca-certificates ipmitool smartmontools zfs sysstat tzdata && \
    rm -f /bin/iostat

ENV TZ=UTC
ENV PATH=/bin:/usr/bin:/sbin:/usr/sbin
ENV USER=root

EXPOSE 5454
ENTRYPOINT ["/notifiarr"]
