FROM ubuntu:26.04@sha256:2260313b31c8c011cd2eebe728008efac1b3982be73eb71348ea2648d2c0e09b

ARG TARGETPLATFORM
ARG TARGETARCH
COPY --chmod=755 ${TARGETPLATFORM}/notifiarr /notifiarr

RUN DEBIAN_FRONTEND=noninteractive apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates curl smartmontools ipmitool zfsutils-linux sysstat libncurses6 tzdata \
    && curl -sSo /notifiarr.tgz \
        "https://raw.githubusercontent.com/Notifiarr/build-dependencies/main/notifiarr-docker-${TARGETARCH}.tgz" \
    && tar -zxf /notifiarr.tgz -C / \
    && rm -f /notifiarr.tgz \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV TZ=UTC
ENV PATH=/bin:/usr/bin:/sbin:/usr/sbin
ENV USER=root

EXPOSE 5454
ENTRYPOINT ["/notifiarr"]
