FROM nvidia/cuda:13.3.1-base-ubuntu24.04@sha256:22dc6de51e33966f735440e9601a3006c38a8e6da4b4896b8ebc826e41252ae1

ARG TARGETPLATFORM
ARG TARGETARCH
COPY --chmod=755 ${TARGETPLATFORM}/notifiarr /notifiarr

RUN DEBIAN_FRONTEND=noninteractive apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates curl smartmontools ipmitool zfsutils-linux sysstat libncurses6 tzdata \
    && curl -sSo /notifiarr.tgz \
        "https://raw.githubusercontent.com/Notifiarr/build-dependencies/main/notifiarr-docker-${TARGETARCH}.tgz" \
    && tar -zxf /notifiarr.tgz -C / \
    && rm -f /notifiarr.tgz \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV DN_SNAPSHOT_NVIDIA_SMI_PATH=/usr/bin/nvidia-smi
ENV TZ=UTC
ENV PATH=/bin:/usr/bin:/sbin:/usr/sbin
ENV USER=root

EXPOSE 5454
ENTRYPOINT ["/notifiarr"]
