#!/bin/bash -x

# Deploys a new homebrew formula file to a github homebrew formula repo: $HBREPO
# Requires SSH credentials in ssh-agent to work.
# Run by Travis-CI when a new release is created on GitHub.
# Do not edit this file.

source settings.sh

SHA256=$(curl -sL https://github.com/Notifiarr/notifiarr/archive/v${VERSION}.tar.gz | openssl dgst -r -sha256 | awk '{print $1}')

# Creating formula from template using sed.
sed -e "s/{{Version}}/${VERSION}/g" \
  -e "s/{{Iter}}/${ITERATION}/g" \
  -e "s/{{SHA256}}/${SHA256}/g" \
  -e "s/{{Desc}}/${DESC}/g" \
  -e "s%{{SOURCE_URL}}%${SOURCE_URL}%g" \
  -e "s%{{SOURCE_PATH}}%${SOURCE_PATH}%g" \
  init/homebrew/service.rb.tmpl | tee notifiarr.rb

mkdir $HOME/.ssh
HB_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"
echo "${HOMEBREW_DEPLOY_KEY}" > "${HB_FILE}"
chmod 600 "${HB_FILE}"
printf "%s\n" \
  "Host github.com-hbrepo" \
  "  HostName github.com" \
  "  IdentityFile ${HB_FILE}" \
  "  StrictHostKeyChecking no" \
  "  LogLevel ERROR" >> $HOME/.ssh/config

git config --global user.email "notifiarr@auto.releaser"
git config --global user.name "notifiarr-auto-releaser"

rm -rf homebrew_release_repo
git clone git@github.com-hbrepo:golift/homebrew-mugs.git homebrew_release_repo

mv notifiarr.rb homebrew_release_repo/Formula
pushd homebrew_release_repo
git add Formula/notifiarr.rb
git commit -m "Update notifiarr on Release: v${VERSION}-${ITERATION}"
git push
popd
