name: frontend
on:
  pull_request:
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - name: npm ci
        run: npm ci
      - name: svelte-check
        run: npm run check
        continue-on-error: true
      - name: eslint
        run: npm run lint
      - name: prettier
        run: npm run format:check
        continue-on-error: true
